version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l

  install:
    desc: Install the dependencies
    cmds:
      - poetry install

  test:
    desc: Run the tests
    cmds:
      - poetry run pytest

  format:
    desc: Reformat the code
    cmds:
      - poetry run ruff format
